#!/usr/bin/env python3
"""Render or extract the Recruiter Contacts tracker HTML.

Two subcommands:

  extract <html_path>
      Print the rows array (as JSON) from an existing tracker HTML file to stdout.
      Used when refreshing an existing tracker, so the caller can merge new
      contacts into the existing list without clobbering hand-edited notes.

  render <output_path>
      Read a JSON array of rows from stdin and write a freshly rendered tracker
      HTML to <output_path>, using assets/tracker_template.html as the template.

Row schema (each row is a dict):
  name, company, role, email, date (YYYY-MM-DD), type, notes
  type in {"active", "warm", "referrer", "cold", "stale"}
"""

from __future__ import annotations

import argparse
import datetime
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TEMPLATE_PATH = ROOT / "assets" / "tracker_template.html"

# Markers used inside the template to delimit the embedded rows array.
# Keep these stable — the extract command depends on them.
ROWS_RE = re.compile(
    r"/\*\s*ROWS:BEGIN\s*\*/(?P<body>.*?)/\*\s*ROWS:END\s*\*/",
    re.DOTALL,
)
DATE_PLACEHOLDER = "__GENERATED_DATE__"


def _quote_unquoted_keys(js_array_src: str) -> str:
    """Best-effort: turn `{name: "Foo"}` into `{"name": "Foo"}` so json.loads can parse.

    This is a fallback for tracker files that were generated by an earlier version
    of the template (which used JS-object literal syntax). We only quote bare
    identifiers that appear right after `{` or `,` and before `:`.
    """
    pattern = re.compile(r'([{,]\s*)([A-Za-z_][A-Za-z0-9_]*)(\s*:)')
    return pattern.sub(r'\1"\2"\3', js_array_src)


def extract(html_path: Path) -> None:
    """Write embedded tracker rows as JSON, using legacy JS syntax as a fallback."""
    html = html_path.read_text(encoding="utf-8")
    m = ROWS_RE.search(html)
    if not m:
        # Legacy template without markers — try to find `const rows = [...];`
        legacy = re.search(r"const\s+rows\s*=\s*(\[.*?\])\s*;", html, re.DOTALL)
        if not legacy:
            json.dump([], sys.stdout)
            return
        body = legacy.group(1)
    else:
        body = m.group("body").strip()

    # Try strict JSON first.
    try:
        rows = json.loads(body)
    except json.JSONDecodeError:
        # Fall back: drop trailing commas + quote bare keys, then retry.
        cleaned = re.sub(r",(\s*[\]}])", r"\1", body)
        cleaned = _quote_unquoted_keys(cleaned)
        try:
            rows = json.loads(cleaned)
        except json.JSONDecodeError as e:
            sys.stderr.write(f"[render_tracker] could not parse rows: {e}\n")
            sys.stderr.write(
                "Tip: open the HTML, copy the contents of the const rows = [...] array, "
                "and pipe a clean JSON version into `render` to regenerate.\n"
            )
            sys.exit(2)

    json.dump(rows, sys.stdout, indent=2, ensure_ascii=False)


def render(output_path: Path, rows: list) -> None:
    """Render rows into the marked template region and stamp today's generation date."""
    template = TEMPLATE_PATH.read_text(encoding="utf-8")
    rows_json = json.dumps(rows, indent=2, ensure_ascii=False)

    # Replace the marked region with the new rows. The template ships with
    # an empty array between the markers, but we don't depend on that — we
    # match whatever is currently between the markers and swap it.
    def _swap(match: re.Match) -> str:
        return f"/* ROWS:BEGIN */{rows_json}/* ROWS:END */"

    new_html, count = ROWS_RE.subn(_swap, template, count=1)
    if count != 1:
        sys.stderr.write(
            "[render_tracker] template is missing /* ROWS:BEGIN */ ... /* ROWS:END */ markers\n"
        )
        sys.exit(3)

    new_html = new_html.replace(DATE_PLACEHOLDER, datetime.date.today().isoformat())

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(new_html, encoding="utf-8")
    sys.stderr.write(f"[render_tracker] wrote {len(rows)} contacts to {output_path}\n")


def main() -> None:
    """Dispatch extract/render commands, rejecting missing files and non-array JSON."""
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="cmd", required=True)

    pe = sub.add_parser("extract", help="Print rows JSON from an existing tracker HTML to stdout.")
    pe.add_argument("html_path", type=Path)

    pr = sub.add_parser("render", help="Read rows JSON from stdin and write tracker HTML to <output_path>.")
    pr.add_argument("output_path", type=Path)

    args = parser.parse_args()

    if args.cmd == "extract":
        if not args.html_path.exists():
            sys.stderr.write(f"[render_tracker] file does not exist: {args.html_path}\n")
            sys.exit(1)
        extract(args.html_path)
    elif args.cmd == "render":
        try:
            rows = json.load(sys.stdin)
        except json.JSONDecodeError as e:
            sys.stderr.write(f"[render_tracker] stdin is not valid JSON: {e}\n")
            sys.exit(2)
        if not isinstance(rows, list):
            sys.stderr.write("[render_tracker] expected a JSON array of row objects on stdin\n")
            sys.exit(2)
        render(args.output_path, rows)


if __name__ == "__main__":
    main()
